import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>蔀(Shetommy/@st43/@0si43)のWebサイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/profile.jpg" />
      </Head>

      <div className={styles.profileImage}>
        <Image src="/profile.jpg" alt="Avatar" width={200} height={200} />
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}>蔀のページへようこそ</h1>
      </main>

      <footer className={styles.footer}>
        Copyright © Shetommy All Rights Reserved.
      </footer>
    </div>
  )
}
